// Mocks generated by Mockito 5.4.5 from annotations
// in saasfork_firebase_service/test/cloud_functions/stripe_functions_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:cloud_functions/cloud_functions.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:saasfork_firebase_service/cloud_functions/stripe_functions.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHttpsCallableResult_0<T> extends _i1.SmartFake
    implements _i2.HttpsCallableResult<T> {
  _FakeHttpsCallableResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirebaseFunctionsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFunctionsService extends _i1.Mock
    implements _i3.FirebaseFunctionsService {
  MockFirebaseFunctionsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HttpsCallableResult<dynamic>> callFunction(
    String? functionName,
    Map<String, dynamic>? parameters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#callFunction, [functionName, parameters]),
            returnValue: _i4.Future<_i2.HttpsCallableResult<dynamic>>.value(
              _FakeHttpsCallableResult_0<dynamic>(
                this,
                Invocation.method(#callFunction, [functionName, parameters]),
              ),
            ),
          )
          as _i4.Future<_i2.HttpsCallableResult<dynamic>>);
}
